[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  # OpenZeppelin non-upgradeable
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
  # OpenZeppelin upgradeable (IERC, ERC721EnumerableUpgradeable, AccessControlUpgradeable, Proxy, UUPS…)
  "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  # Chainlink VRF, oracles…
  "chainlink/=lib/chainlink/",
  # Forge-std pour Test.sol, Script.sol…
  "forge-std/=lib/forge-std/src/"
]
